### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by CheaterAdams** [JVital2013/goesbetween#1]
I was hoping for some installation instructions (Windows and Linux).

I see from the file extensions this must be C# code. I am not familiar with C# but research tells me I can use csc on Windows to compile the code but that's all I know. 
For Linux looks like something called mono is needed.

Would you please provide some details.

Thanks

**Comment by JVital2013** [comment]
**If you're just looking to run the program, pre-compiled releases are available from the releases page at** [https://github.com/JVital2013/goesbetween/releases](https://github.com/JVital2013/goesbetween/releases). I have builds for Windows, macOS, and Linux (x64 and ARM). The pre-compiled versions have no dependencies, and can be run right away after extracting the archive. I'm guessing this is what you want.

**If you need to compile it yourself:** this is actually written in .NET 6, which can be cross-compiled for nearly any platform from Visual Studio. Install Visual Studio 2022 on a Windows Machine, and clone the repository. Once this repo is loaded in Visual Studio, make your desired changes and "publish" it for your target platform. You can read about publishing a .NET app at [https://learn.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs157#tabpanel_1_vs157](https://learn.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs157#tabpanel_1_vs157).

I've already built publish profiles for all common system configurations, but you can cross-compile for some additional platforms as well.

**Comment by CheaterAdams** [comment]
Excellent. Thanks for your prompt response.
